AWSTemplateFormatVersion: "2010-09-09"
Description: Create S3
# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
  SystemName:
    Description: "System name of each resource names."
    Type: String
    Default: "gr"
  EnvName:
    Description: "Environment name of each resource names."
    Type: String
    Default: "product"
  BucketName:
    Description: "Bucket name."
    Type: String
    Default: "bucket"
# ------------------------------------------------------------#
# Create S3 Bucket
# ------------------------------------------------------------# 
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${SystemName}-${EnvName}-${BucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${SystemName}-lifecycle-bucket
            # Prefix: Backup/
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-${BucketName}
        - Key: Env
          Value: !Sub ${EnvName}
#------------------------------------------------------------
# Output Parameters
#------------------------------------------------------------
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${EnvName}-${BucketName}