AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  SystemName:
    Description: "System name of each resource names."
    Type: String
    Default: "gr"
  EnvName:
    Description: "Environment name of each resource names."
    Type: String
    Default: "product"
  KeyPairName: 
    Description: gr-product-ec2 EC2 Key Pair
    Type: String
    Default: gr-product-ec2-key
  EC2AMI: 
    Description: gr-product-ec2 EC2 AMI
    Type: String
    Default: ami-02d081c743d676996
  InstanceType:
    Description: gr-product-ec2 EC2 instance type
    Type: String
    Default: t2.micro
# ------------------------------------------------------------#
#  Create EC2 Instance 
# ------------------------------------------------------------#
Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyPairName
  EC2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref NewKeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: { "Fn::ImportValue": !Sub "${EnvName}-web-subnet-1a" }
          GroupSet:
          - Fn::ImportValue: !Sub ${EnvName}-ec2-sg-a
          AssociatePublicIpAddress: false
      IamInstanceProfile: 
        Fn::ImportValue: !Sub ${EnvName}-ec2-role
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
            Encrypted : true
      UserData: !Base64 | 
            #!/bin/bash
            yum update -y
            yum install httpd-2.4.51 -y
            systemctl start httpd
            systemctl enable httpd
            httpd -v
            cp /usr/share/httpd/noindex/index.html /var/www/html/index.html
      Tags: 
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-ec2-a
        - Key: Env
          Value: !Sub ${EnvName}
  EC2InstanceB:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref NewKeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: { "Fn::ImportValue": !Sub "${EnvName}-web-subnet-1a" }
          GroupSet:
          - Fn::ImportValue: !Sub ${EnvName}-ec2-sg-b
          AssociatePublicIpAddress: false
      IamInstanceProfile: 
        Fn::ImportValue: !Sub ${EnvName}-ec2-role
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
            Encrypted : true
      Tags: 
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-ec2-b
        - Key: Env
          Value: !Sub ${EnvName}
# ------------------------------------------------------------
# Output Parameters
# ------------------------------------------------------------
Outputs:
# EC2
  EC2InstanceA:
    Value: !Ref EC2InstanceA
    Export:
      Name: !Sub ${EnvName}-ec2-a
  EC2InstanceB:
    Value: !Ref EC2InstanceB
    Export:
      Name: !Sub ${EnvName}-ec2-b