AWSTemplateFormatVersion: "2010-09-09"
Description: Create API Gateway & Lambda
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  SystemName:
    Description: "System name of each resource names."
    Type: String
    Default: "gr"
  EnvName:
    Description: "Environment name of each resource names."
    Type: String
    Default: "product"
# ------------------------------------------------------------#
#  Create REST API 
# ------------------------------------------------------------#
Resources :
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table # DynamoDB 테이블의 Id, name, description 항목은 콘솔 화면에서 별도로 생성하도록 합시다.
    Properties:
      TableName: !Sub ${SystemName}-${EnvName}-db
      AttributeDefinitions:
        - AttributeName: id # 파티션 키
          AttributeType: S  # 파티션 키는 문자열
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST  # 온디맨드 모드
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-dynamoDB
        - Key: Env
          Value: !Sub ${EnvName}